apiVersion: v1
kind: Service
metadata:
  name: ftb-server
spec:
  selector:
    app: ftb
  ports:
  - port: 1025
    targetPort: 1025
    nodePort: 31101
    protocol: TCP
    name: ftb-server
  externalTrafficPolicy: Local
  type: NodePort 
