apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: argocd-base
  namespace: argocd
  finalizers:
    - resources.finalizer.argocd.argoproj.io
spec:
  project: argocd
  source:
    repoURL: https://github.com/noahtutt/home-argo-deployments
    targetRevision: HEAD
    path: argo-config/kustomize/base
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true

