apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: foundry
  namespace: argocd
  finalizers:
    - resources.finalizer.argocd.argoproj.io
spec:
  project: homelab
  source:
    repoURL: https://github.com/noahtutt/home-argo-deployments
    targetRevision: HEAD
    path: foundry/kustomize/base
  destination:
    namespace: foundry 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true

