apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: rook-ceph
  namespace: argocd
  finalizers:
    - resources.finalizer.argocd.argoproj.io
spec:
  project: rook-ceph
  source:
    repoURL: https://github.com/noahtutt/home-argo-deployments
    targetRevision: HEAD
    path: rook-ceph/kustomize/base
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ApplyOutOfSyncOnly=true

