apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- application-base.yaml
- project-homelab.yaml
- project-argocd.yaml
- application-argo-deployment.yaml
  #- application-cert-manager.yaml
