apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: homelab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Homelab cluster project
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  destinations:
    - namespace: homelab
      server: https://kubernetes.default.svc
    - namespace: n8kicker
      server: https://kubernetes.default.svc
    - namespace: pihole
      server: https://kubernetes.default.svc
