apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cert Manager project 
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration
    - group: 'cert-manager.io'
      kind: ClusterIssuer
    - group: ''
      kind: Namespace
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
