apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry
  labels:
    app: foundry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundry
  template:
    metadata:
      labels:
        app: foundry
        name: foundry
    spec:
      dnsPolicy: "ClusterFirst"
      containers:
      - name: foundry
        image: felddy/foundryvtt:12.331
        env:
          - name: FOUNDRY_USERNAME
            valueFrom:
              secretKeyRef:
                name: foundry-login
                key: username
          - name: FOUNDRY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: foundry-login
                key: password
          - name: FOUNDRY_ADMIN_KEY
            valueFrom:
              secretKeyRef:
                name: foundry-admin
                key: key
        volumeMounts:
        - name: foundry-data-volume
          mountPath: "/data"
        resources:
          requests:
            memory: 500Mi
            cpu: 100m 
            ephemeral-storage: 1G
          limits:
            memory: 12G
            cpu: 4000m 
            ephemeral-storage: 2G
        ports:
        - containerPort: 30000
          name: foundry-server
      volumes:
      - name: foundry-data-volume
        persistentVolumeClaim:
          claimName: foundry-data-claim
