apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foundry
spec:
  secretName: foundry 
  dnsNames:
  - foundry.noahtutt.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
