apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-ceph-mon-0
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/mapper/debian--k8s--node--0--vg-rook--ceph--mon-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - debian-k8s-node-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-ceph-mon-1
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/mapper/debian--k8s--node--0--vg-rook--ceph--mon-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - debian-k8s-node-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-ceph-blockstorage
spec:
  capacity:
    storage: 200Gi
  volumeMode: Block
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-storage
  local:
    path: /dev/mapper/debian--k8s--node--0--vg-rook--ceph--blockstorage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - debian-k8s-node-0
