apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rook-ceph-server
spec:
  secretName: tls-rook-ceph-server
  dnsNames:
  - ceph.noahtutt.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
