apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8kicker
  labels:
    app: n8kicker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: n8kicker
  template:
    metadata:
      labels:
        app: n8kicker
    spec:
      containers:
      - name: n8kicker
        image: noahtutt/n8kicker:latest
        env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef: 
                name: n8kicker-bot-token
                key: token
