apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mc-map
spec:
  secretName: mc-map 
  dnsNames:
  - mc.noahtutt.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
