apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- tls-argocd-server.yaml
- ingress.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    path: accept-http.yaml
