apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-argocd-server
spec:
  secretName: tls-argocd-server
  dnsNames:
  - argo.noahtutt.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
