apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon
  labels:
    app: falcon 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcon 
  template:
    metadata:
      labels:
        app: falcon 
    spec:
      containers:
      - name: falcon 
        image: ubuntu
        command:
          - "sleep"
          - "604800"
