apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-mystery
  labels:
    app: falcon-mystery 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcon-mystery 
  template:
    metadata:
      labels:
        app: falcon-mystery 
    spec:
      containers:
      - name: falcon-mystery 
        image: falcon-mystery
        imagePullPolicy: IfNotPresent
