apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
spec:
 acme:
   email: noah@noahtutt.dev 
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: letsencrypt-staging-issuer-account-key
   solvers:
     - http01:
         ingress:
           class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
spec:
 acme:
   email: noah@noahtutt.dev 
   server: https://acme-v02.api.letsencrypt.org/directory 
   privateKeySecretRef:
     name: letsencrypt-staging-issuer-account-key
   solvers:
     - http01:
         ingress:
           class: traefik
