apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foundry-jed
spec:
  secretName: foundry-jed
  dnsNames:
  - foundry2.noahtutt.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
