apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- volume-claim.yaml
- tls-pihole-dashboard.yaml
